Controllers/FacilityController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using organProject.Models;

//***************************
using System.Text.RegularExpressions;
//**************************

namespace organProject.Controllers  
{
    public class FacilityController : Controller   
    {
        private MyContext _context;

        public FacilityController(MyContext context)
        {
            _context = context;
        }

        [HttpGet("/facility")]     
        public IActionResult LogReg()
        {
            return View("LogReg"); 
        }

//==========================================================================

        [HttpPost("facility/user/create")]
        public IActionResult CreateUser(LogRegWrapper Form)
        {
            if(ModelState.IsValid)
            {
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                Form.NewUser.Password = Hasher.HashPassword(Form.NewUser, Form.NewUser.Password);

                _context.Add(Form.NewUser);
                _context.SaveChanges();

                User ThisUser = _context.Users.FirstOrDefault(i => i.Email == Form.NewUser.Email);
                HttpContext.Session.SetInt32("UserID", ThisUser.UserID);

                return RedirectToAction("Dashboard");
            }
            return View("LogReg");
        }

//=========================================================================================

        [HttpPost("facility/user/checklogin")]
        public IActionResult Verify(LogRegWrapper Form)
        {
            if(ModelState.IsValid)
            {
                var inDB = _context.Users.FirstOrDefault(u => u.Email == Form.LoginUser.Email);

                if(inDB == null)
                {
                    ModelState.AddModelError("Email", "Invalid Email/Passoword");
                    return View("LogReg");
                }
                var hasher = new PasswordHasher<LoginUser>();
                var result = hasher.VerifyHashedPassword(Form.LoginUser , inDB.Password, Form.LoginUser.Password);

                if(result == 0)
                {
                    ModelState.AddModelError("Password", "Are you sure you belong here?");
                    return View("LogReg");
                }

                User ThisUser = _context.Users.FirstOrDefault(u => u.Email == Form.LoginUser.Email);
                
                HttpContext.Session.SetInt32("UserID", ThisUser.UserID);
                
                return RedirectToAction("Dashboard");
                
            }

            return View("LogReg");
        }

//======================================================================================

        [HttpGet("facility/logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("LogReg");
        }

//=============================================================================================

        [HttpGet("/facility/dashboard")]
        public IActionResult Dashboard()
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("LogReg");
            }

            FacilityDashWrapper DashWrap = new FacilityDashWrapper();
            DashWrap.ThisUser = _context.Users.FirstOrDefault(s => s.UserID == userid);

            DashWrap.AllCenter = _context.Centers
            .Include(r => r.Recipients)
            .ToList();

            DashWrap.AllRecipient = _context.Recipients
            .Include(q => q.CurrentCenter)
            .ThenInclude(e => e.Recipients)
            .ToList();

            return View("Dashboard", DashWrap);
        }

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        [HttpGet("/facility/add/patient")]
        public IActionResult AddPatient()
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("LogReg");
            }

            NewPatientWrap NewPtWrap = new NewPatientWrap();
            NewPtWrap.ThisUser = _context.Users.FirstOrDefault(p => p.UserID == userid);
            NewPtWrap.AllCenter = _context.Centers
            .Include(r => r.Recipients).ToList();

            return View("AddPatient", NewPtWrap);

        }


//************************************************************************

        [HttpPost("/facility/add/patient")]
        public IActionResult CreatePatient(NewPatientWrap Form)
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("LogReg");
            }

            if(ModelState.IsValid)
            {
                _context.Add(Form.NewRecipient);
                _context.SaveChanges();

                return RedirectToAction("AddPatient");

            }

            return AddPatient();
        }

        [HttpGet("/facility/add/center")]
        public IActionResult AddCenter()
        {
            return View("AddCenter");
        }
        [HttpPost("/facility/add/center")]
        public IActionResult CreateCenter(Center Form)
        {
            _context.Add(Form);
            _context.SaveChanges();

            return View("AddCenter");
        }

        [HttpGet("/facility/listcenter")]
        public IActionResult ListCenter()
        {
            NewPatientWrap justList = new NewPatientWrap();

            justList.AllCenter = _context.Centers.ToList();

            return View("ListCenter", justList);
        }

        [HttpGet("/facility/delete/patient/{id}")]
        public IActionResult DeletePatient(int id)
        {
            Recipient ToDelete = _context.Recipients.FirstOrDefault(o => o.RecipientID == id);
            _context.Remove(ToDelete);
            _context.SaveChanges();


            return RedirectToAction("Dashboard");
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using organProject.Models;

//***************************
using System.Text.RegularExpressions;
//**************************

namespace organProject.Controllers  
{
    public class HomeController : Controller   
    {
        private MyContext _context;

        public HomeController(MyContext context)
        {
            _context = context;
        }

        [HttpGet("")]     
        public IActionResult Switch()
        {
            return View("Switch"); 
        }

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        [HttpGet("/logreg")]
        public IActionResult Index()
        {
            return View("Index");
        }

//==========================================================================

        [HttpPost("/user/create")]
        public IActionResult CreateUser(LogRegWrapper Form)
        {
            if(ModelState.IsValid)
            {
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                Form.NewUser.Password = Hasher.HashPassword(Form.NewUser, Form.NewUser.Password);

                _context.Add(Form.NewUser);
                _context.SaveChanges();

                User ThisUser = _context.Users.FirstOrDefault(i => i.Email == Form.NewUser.Email);
                HttpContext.Session.SetInt32("UserID", ThisUser.UserID);

                return RedirectToAction("Dashboard");
            }
            return View("Index");
        }

//=========================================================================================

        [HttpPost("/user/checklogin")]
        public IActionResult Verify(LogRegWrapper Form)
        {
            if(ModelState.IsValid)
            {
                var inDB = _context.Users.FirstOrDefault(u => u.Email == Form.LoginUser.Email);

                if(inDB == null)
                {
                    ModelState.AddModelError("Email", "Invalid Email/Passoword");
                    return View("Index");
                }
                var hasher = new PasswordHasher<LoginUser>();
                var result = hasher.VerifyHashedPassword(Form.LoginUser , inDB.Password, Form.LoginUser.Password);

                if(result == 0)
                {
                    ModelState.AddModelError("Password", "Are you sure you belong here?");
                    return View("Index");
                }

                User ThisUser = _context.Users.FirstOrDefault(u => u.Email == Form.LoginUser.Email);
                
                HttpContext.Session.SetInt32("UserID", ThisUser.UserID);
                
                return RedirectToAction("Dashboard");
                
            }

            return View("Index");
        }

//======================================================================================

        [HttpGet("/logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

//=============================================================================================

        [HttpGet("/dashboard")]
        public IActionResult Dashboard()
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("Index");
            }

            DashWrapper DashWrap = new DashWrapper();
            DashWrap.ThisUser = _context.Users.FirstOrDefault(s => s.UserID == userid);

            DashWrap.AllDonors = _context.Donors
            .Include(q => q.CurrentCenter)
            .ToList();

            return View("Dashboard", DashWrap);
        }

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        [HttpGet("/add/donor")]
        public IActionResult NewDonor()
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("Index");
            }

            NewDonorWrap NewDonorWrap = new NewDonorWrap();
            NewDonorWrap.ThisUser = _context.Users.FirstOrDefault(p => p.UserID == userid);
            NewDonorWrap.AllCenter = _context.Centers.ToList();
            
            return View("NewDonor");
        }


//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++


        [HttpPost("/add/donor")]
        public IActionResult CreateDonor(NewDonorWrap Form)
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("Index");
            }

            if(ModelState.IsValid)
            {
                _context.Add(Form.NewDonor);
                _context.SaveChanges();

                return RedirectToAction("Dashboard");
            }

            return NewDonor();
        }


//+++++++++++++++++++++++++++++++++++++++++++++++++++++


        [HttpPost("/add/center")]
        public IActionResult CreateCenter(Center Form)
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("Index");
            }

            if(ModelState.IsValid)
            {
                _context.Add(Form);
                _context.SaveChanges();

                return RedirectToAction("Dashboard");
            }

            return NewCenter();
        }

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        [HttpGet("/add/center")]
        public IActionResult NewCenter()
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("Index");
            }
            
            Center NewCenter = new Center();

            return View("NewCenter");
        }

//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        [HttpGet("/find/matches/{id}")]
        public IActionResult FindMatch(int id)
        {
            int? userid = HttpContext.Session.GetInt32("UserID");

            if(userid == null)
            {
                return RedirectToAction("Index");
            }

            MatchWrap MatchWrap = new MatchWrap();

            MatchWrap.ThisUser = _context.Users.FirstOrDefault(r => r.UserID == userid);
            Donor ThisDonor = _context.Donors.FirstOrDefault(o => o.DonorID == id);
            MatchWrap.ThisDonor = ThisDonor;
            MatchWrap.Potential = _context.Recipients
            .Include(e => e.CurrentCenter)
            .Where(b => b.BloodType == ThisDonor.BloodType && b.Rh == ThisDonor.Rh).ToList();

            return View("PotentialMatch", MatchWrap);
        }


    }
}

Views/Home/Dashboard.cshtml
@using organProject.Models;
@model DashWrapper;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <div class="container">
        <h1>Welcome @Model.ThisUser.FirstName</h1>
        <div class="table">
            <h3>The Current List</h3>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Donor Name</th>
                        <th>DOB</th>
                        <th>Blood Type</th>
                        <th>Registered</th>
                        <th>Family Consent</th>
                        <th>Find Matches</th>
                        <th>Notes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(Donor d in @Model.AllDonors)
                    {
                        <tr>
                            <td>@d.DonorID</td>
                            <td>@d.LastName, @d.FirstName</td>
                            <td>@d.DOB.ToShortDateString()</td>
                            <td>@if(d.BloodType == 'C')
                                {
                                    <span>AB</span>
                                }
                                else
                                {
                                    @d.BloodType
                                }
                            @if(d.Rh == true)
                            {
                                <span>Positive</span>
                            }
                            else
                            {
                                <span>Negative</span>
                            }
                            </td>
                            <td>@if(d.Registered == true)
                                {
                                    <span>Registered</span>
                                }
                                else
                                {
                                    <span>NOT Registered</span>
                                }
                            </td>
                            <td>@if(d.Consent == true)
                                {
                                    <span>Consented</span>
                                }
                                else
                                {
                                    <span>NOT Concented</span>
                                }
                            </td>
                            <td><button onclick="window.location.href='/find/matches/@d.DonorID'">Find Matches</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <button onclick="window.location.href='/add/donor'">Add Donor</button>
    </div>
</body>
</html>

Views/Home/Index.cshtml
@using organProject.Models;
@model LogRegWrapper;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <div class="container">
        <h1>Please Login or Register to continue</h1>
        <div class="register">
            <h1>New User Register</h1>
                <form asp-action="CreateUser" method="post">

                <span asp-validation-for="NewUser.FirstName"></span>
                <br>

                <label asp-for="NewUser.FirstName"></label>
                <input asp-for="NewUser.FirstName">
                <br>

                <span asp-validation-for="NewUser.LastName"></span>
                <br>

                <label asp-for="NewUser.LastName"></label>
                <input asp-for="NewUser.LastName">
                <br>


                <span asp-validation-for="NewUser.Email"></span>
                <br>

                <label asp-for="NewUser.Email"></label>
                <input asp-for="NewUser.Email">
                <br>

                <span asp-validation-for="NewUser.Password"></span>
                <br>

                <label asp-for="NewUser.Password"></label>
                <input asp-for="NewUser.Password">
                <br>

                <span asp-validation-for="NewUser.Confirm"></span>
                <br>

                <label asp-for="NewUser.Confirm"></label>
                <input asp-for="NewUser.Confirm">
                <br>

                <button type="submit">Submit</button>

            </form>
        </div>
        <div class="login">
            <h1>Login</h1>
            <form asp-action="Verify" method="post">
                <span asp-validation-for="LoginUser.Email"></span>
                <br>
                <label asp-for="LoginUser.Email"></label>
                <input asp-for="LoginUser.Email">
                <br>
                <span asp-validation-for="LoginUser.Password"></span>
                <br>
                <label asp-for="LoginUser.Password"></label>
                <input asp-for="LoginUser.Password">
                <br>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</body>
</html>

Views/Home/NewDonor.cshtml
@using organProject.Models;
@model NewDonorWrap;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Donor</title>
</head>
<body>
    <div class="">
        <h1>Add Donor Here</h1>
        <div class="form">
            <form asp-action="/add/donor" method="post">
                <span asp-validation-for="@Model.NewDonor.FirstName"></span>
                <br>
                <label asp-for="@Model.NewDonor.FirstName"></label>
                <input asp-for="@Model.NewDonor.FirstName">
                <br>
                <span asp-validation-for="@Model.NewDonor.LastName"></span>
                <br>
                <label asp-for="@Model.NewDonor.LastName"></label>
                <input asp-for="@Model.NewDonor.LastName">
                <br>
                <span asp-validation-for="@Model.NewDonor.DOB"></span>
                <br>
                <label asp-for="@Model.NewDonor.DOB"></label>
                <input asp-for="@Model.NewDonor.DOB">
                <br>
                <span asp-validation-for="@Model.NewDonor.BloodType"></span>
                <br>
                <label asp-for="@Model.NewDonor.BloodType"></label>
                <select asp-for="@Model.NewDonor.BloodType" >
                    <option value="A">A</option>
                    <option value="B">B</option>
                    <option value="C">AB</option>
                    <option value="O">O</option>
                </select>
                <input asp-for="@Model.NewDonor.BloodType">
                <br>
                <span asp-validation-for="@Model.NewDonor.Rh"></span>
                <br>
                <label asp-for="@Model.NewDonor.Rh"></label>
                <input asp-for="@Model.NewDonor.Rh">
                <br>
                <span asp-validation-for="@Model.NewDonor.Registered"></span>
                <br>
                <label asp-for="@Model.NewDonor.Registered"></label>
                <input asp-for="@Model.NewDonor.Registered">
                <br>
                <span asp-validation-for="@Model.NewDonor.Consent"></span>
                <br>
                <label asp-for="@Model.NewDonor.Consent"></label>
                <input asp-for="@Model.NewDonor.Consent">
                <br>
                @* <span asp-validation-for="@Model.NewDonor.CurrentCenter"></span>
                <br>
                <label asp-for="@Model.NewDonor.CurrentCenter"></label>
                <select asp-for="@Model.NewDonor.CurrentCenter">
                    @foreach(Center c in @Model.AllCenter)
                    {
                        <option asp-value="@c.CenterID">@c.CenterName</option>

                    }
                </select> *@
                <br>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</body>
</html>

Views/Home/PotentialMatch.cshtml
@using organProject.Models;
@model MatchWrap;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Potential matches</title>
</head>
<body>
    <div class="container">
        <h1>Potential Matches for @Model.ThisDonor.FirstName</h1>
           <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Patinet Name</th>
                        <th>DOB</th>
                        <th>Blood Type</th>
                        <th>Location</th>
                        <th>Notes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(Recipient d in @Model.Potential)
                    {
                        <tr>
                            <td>@d.RecipientID</td>
                            <td>@d.LastName, @d.FirstName</td>
                            <td>@d.DOB.ToShortDateString()</td>
                            <td>@if(d.BloodType == 'C')
                                {
                                    <span>AB</span>
                                }
                                else
                                {
                                    @d.BloodType
                                }
                            @if(d.Rh == true)
                            {
                                <span>Positive</span>
                            }
                            else
                            {
                                <span>Negative</span>
                            }
                            </td>
                            <td>@d.CurrentCenter.CenterName</td>
                        </tr>
                    }
                </tbody>
            </table>
    </div>
</body>
</html>

Views/Home/Switch.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select</title>
</head>
<body>
    <div class="container">
        <div class="boots">
            <h1>Click here for ORC access</h1>

            <button onclick="location.href='/logreg'">ORC</button>
        </div>
        <div class="chairs">
            <h1>Click here for Facility access</h1>
            <button onclick="location.href='/facility'">Facility</button>
        </div>
    </div>
</body>
</html>




            @* <button onclick="location.href='@Url.Action("actionname", "controllername")'" asp-controller="Facility"></button> *@